
#
# 自动化语言
# 根据服务器和玩家本地语言，来查找language文件夹中支持的语言文件，
# 并为服务器和玩家本地化翻译，没有受支持的语言文件将强制默认使用en_US.yml中的语言。
#
language: "zh_CN"

#
# 自动重载(配置时开启，非配置状态关闭以减少0.001略微性能)
# 当配置文件发生修改时插件会自动重新载入无需输入命令
# 必须重启或者彻底重新加载插件才会生效！
#
autoReload:
  enable: true
  # 单位为秒
  period: 5

#
# 自动保存数据（单位：秒）
# 定期为所有在线的玩家保存数据，如果您的是服务器长期稳定可不开启。
#
autoSave:
  enable: true
  period  : 300

#
# 每次开服都会根据你的服务器生成宝可梦列表，以便方便您快速配置！
#
generatePokemonList: true